### ISSUE TITLE
prepareGenFromBeagle4 boost lib paths

### ISSUE THREAD

**Issue by kutsukos** [molgenis/ngs-utils#184]
Hello.

I am having a problem on using prepareGenFromBeagle4 for a pipeline for ShapeIt.
I have downloaded libboost and but it seems that in makefile of prepareGenFromBeagle4, the path for this library is hard-coded for your machine. So, I have changed it, to work on mine too. 
The only problem now is that I cant find the folder "/apps/software/Boost/1.60.0-foss-2015b-Python-2.7.9/include/ " and I have no idea how to create it.

It will be useful to include a manual for this application or make paths work on every machine.

**Comment by freerkvandijk** [comment]
Dear Ioannis,

the prepareGenFromBeagle4 script is modified for our internal use and indeed contains hard coded paths. The original script can be found on the Shapeit2 webpage here: 

- https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/files/prepareGenFromBeagle4.tgz

and is described here (just search for the term "prepareGenFromBeagle4"): 

- https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html

The original script also contains hard coded paths, I suggest contacting the authors on that webpage with potential changes. 

Regarding the /apps/software/Boost/1.60.0-foss-2015b-Python-2.7.9/include/ path: this should be changed to your own local installation of the Boost libraries.

**Comment by kutsukos** [comment]
I have changed 2 lines in Makefile and the compilation didnt have any errors and the application seems to work all right.

The following are the changed lines 
-36   ICL3P= -I/apps/software/Boost/1.60.0-foss-2015b-Python-2.7.9/include/
+36   ICL3P= -I/usr/local/lib/boost/fusion/include/
-71   OBOST=-lz /apps/software/Boost/1.60.0-foss-2015b-Python-2.7.9/lib/libboost_iostreams.a
+71   OBOST=-lz /usr/local/lib/libboost_iostreams.a

Do you think thats ok? I think that's the only lines containing hard-coded paths.

**Comment by freerkvandijk** [comment]
If it compiled without errors it should be fine. However, we did run into several issues using the software. We've mainly seen two things:
- There are some issues with zlib compression libraries
- If I'm correct the software uses or produces files with an *.gz extension, however they are not bgzipped and you need to uncompress and recompress them using bgzip.
When above things happen the script usually throws an error about an index being out of bounds or number of input and output lines not matching.
